version: '3.7'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
  db:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306      
    environment: 
      - MYSQL_USER=okta
      - MYSQL_PASSWORD=mysecretpasswordissosecure
      - MYSQL_DATABASE=okta
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10      
  insight:
    image: 'redislabs/redisinsight'
    ports:
      - 127.0.0.1:8001:8001
    volumes:
      - redisinsight:/db
  feature-creep-client-dev:
    image: ghcr.io/niekcandaele/featurecreep-client:dev
    ports:
      - 127.0.0.1:3000:5000
volumes:
  redisinsight:
  redis:
  mariadb:
