version: '3.7'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
  db:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  feature-creep-server:
    build:
      context: ./server
    depends_on: 
      - redis
    ports:
      - 127.0.0.1:4000:4000
    environment: 
      - REDIS_HOST=redis
      - NODE_ENV=production
  feature-creep-client:
    build:
      context: ./client
    depends_on: 
      - feature-creep-server
    ports:
      - 127.0.0.1:3000:5000
volumes:
  redis:
  mariadb:
