version: '3.7'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
  # Production mode, uses Cognito for auth
  feature-creep-server:
    image: ghcr.io/niekcandaele/featurecreep-server:latest
    depends_on: 
      - redis
    ports:
      - 127.0.0.1:4000:4000
    environment: 
      - REDIS_HOST=redis
      - NODE_ENV=production
  feature-creep-client:
    image: ghcr.io/niekcandaele/featurecreep-client:latest
    depends_on: 
      - feature-creep-server
    ports:
      - 127.0.0.1:3000:5000
volumes:
  redis:
